server:
  port: 80

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.microsoft.bot: trace
    org.hibernate.SQL: debug
    #org.hibernate.type: trace

# [https://p6spy.readthedocs.io/en/latest/configandusage.html](p6spy_config_guide)
decorator:
  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      tracing:
        include-parameter-values: true

bot:
  ms:
    credentials:
      appId: bbcb1167-2d07-4233-843d-681aa9b5d0b1
      password: 7PVpJLE97RbTvmZ00qzVCHZ7-K.mH~fB_5